### ISSUE TITLE
Please Provide a MSIL DLL at https://www.nuget.org/packages/LottieSharp/

### ISSUE THREAD

**Issue by Schumacher-Bastian** [ascora/LottieSharp#59]
**Is your feature request related to a problem? Please describe.**
Using the NuGet Package from https://www.nuget.org/packages/LottieSharp/2.0.1 in a Project that uses MSIL produces a warning because the Package uses AMD64.

**Describe the solution you'd like**
Distribute a MSIL DLL instead of an AMD64 DLL.

**Describe alternatives you've considered**
I Could change my Project to AMD64

**Additional context**
Translated, (original german warning below):
Severity Code Description Project File Line Suppression State
Warning MSB3270 Conflict between the processor architecture of the project "MSIL" being built and the processor architecture of the reference, "C:\Users\schumacher\.nuget\packages\lottiesharp\2.0.1\lib\net6.0-windows7.0\LottieSharp.dll", "AMD64". This conflict can cause runtime errors. If necessary, use the Configuration Manager to change your project's target processor architecture so that the processor architectures are aligned between your project and the references, or select a reference dependency with a processor architecture that matches your project's target processor architecture.	Ui.Wpf C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets 2302	

original german warning:
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Warnung	MSB3270	Konflikt zwischen der Prozessorarchitektur des Projekts "MSIL", das erstellt wird, und der Prozessorarchitektur des Verweises, "C:\Users\schumacher\.nuget\packages\lottiesharp\2.0.1\lib\net6.0-windows7.0\LottieSharp.dll", "AMD64". Dieser Konflikt kann zu Laufzeitfehlern führen. Ändern Sie ggf. mithilfe des Konfigurations-Managers die als Ziel angegebene Prozessorarchitektur Ihres Projekts so, dass die Prozessorarchitekturen zwischen Ihrem Projekt und den Verweisen ausgerichtet werden, oder wählen Sie eine Abhängigkeit von Verweisen mit einer Prozessorarchitektur, die der als Ziel angegebene Prozessorarchitektur Ihres Projekts entspricht.	Ui.Wpf	C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets	2302

**Comment by sebaJoSt** [comment]
I get the same warning

**Comment by quicoli** [comment]
See release 2.2.0
